@startuml UseCaseDiagram_part2-1
skinparam defaultFontName "Tahoma"
' title "Use Case Diagram: ระบบการจัดการการฝึกงาน"
skinparam nodesep 10
skinparam ranksep 20
left to right direction

actor "เจ้าหน้าที่ฝ่ายงานบริการฯ" as Staff

rectangle "ระบบการจัดการการฝึกงาน" {
  ' กลุ่มเจ้าหน้าที่ (Staff)
    usecase "จัดการข้อมูลสถานประกอบการ" as ucsf003
    usecase "จัดการข่าวประชาสัมพันธ์/ปฏิทินฝึกงาน" as ucsf004
    usecase "ติดตามสถานะขั้นตอนการฝึกงานรายบุคคล" as ucsf005
    usecase "จัดการความคิดเห็น" as ucsf006
    usecase "ตรวจสอบพิจารณาคำร้อง" as ucsf001
    usecase "จัดการเอกสารสำหรับนักศึกษา" as ucsf002

}

' ความสัมพันธ์ของ Staff
Staff -- ucsf001
Staff -- ucsf002
Staff -- ucsf003
Staff -- ucsf004
Staff -- ucsf005
Staff -- ucsf006


' ความสัม

@enduml