@startuml UseCaseDiagram_part1-1

skinparam defaultFontName "Tahoma"
' title "Use Case Diagram: ระบบการจัดการการฝึกงาน"
skinparam nodesep 10
skinparam ranksep 20
left to right direction

actor "นักศึกษา" as Student

rectangle "ระบบการจัดการการฝึกงาน" {
  ' กลุ่มนักศึกษา (Student)
    usecase "จัดการข้อมูลส่วนตัวนักศึกษา" as ucs001
    usecase "ค้นหาข้อมูลสถานประกอบการในระบบ" as ucs002
    usecase "เพิ่มข้อมูลสถานประกอบการ" as ucs003
    usecase "แจ้งความประสงค์" as ucs004
    usecase "อัปโหลดเอกสาร" as ucs005
    usecase "ดาวน์โหลดเอกสารที่ระบบออกให้" as ucs006
    usecase "ตรวจสอบสถานะการยื่นเรื่องของตนเอง" as ucs007
    usecase "จัดการความคิดเห็น" as ucs008
}

' ความสัมพันธ์ของ Student
Student -- ucs001
Student -- ucs002
Student -- ucs003
Student -- ucs004
Student -- ucs005
Student -- ucs006
Student -- ucs007
Student -- ucs008

@enduml