@startuml UseCaseDiagram_part1-2

skinparam defaultFontName "Tahoma"
' title "Use Case Diagram: ระบบการจัดการการฝึกงาน"
skinparam nodesep 10
skinparam ranksep 20
left to right direction

actor "อาจารย์ที่ปรึกษา" as Advisor

rectangle "ระบบการจัดการการฝึกงาน" {
  ' กลุ่มกลุ่มอาจารย์ (Advisor/Teacher)
    usecase "ดูรายชื่อและข้อมูลนักศึกษาในความรับผิดชอบ" as uct001
    usecase "ติดตามสถานะขั้นตอนการฝึกงานของนักศึกษา" as uct002
    usecase "ประเมินผลการฝึกงาน" as uct003
    usecase "จัดการข่าวประชาสัมพันธ์" as uct004
    usecase "จัดการข้อมูลสถานประกอบการ" as uct005
    usecase "จัดการความคิดเห็น" as uct006

}

' ความสัมพันธ์ของ Advisor
Advisor -- uct001
Advisor -- uct002
Advisor -- uct003
Advisor -- uct004
Advisor -- uct005
Advisor -- uct006



@enduml